#!/bin/sh -e

# Meant to be run after installing couchbase (e.g., after rpm/dpkg -i).
#
# Example: ./after-install.sh $NUM_VBUCKETS
#
cp /opt/couchbase/etc/couchdb/default.ini /opt/couchbase/etc/couchdb/default.ini.orig

sed -e "s,os_process_limit = 50,os_process_limit = 0,g" /opt/couchbase/etc/couchdb/default.ini.orig | \
  sed -e "s,;socket_options,socket_options,g" > /opt/couchbase/etc/couchdb/default.ini

echo -e "[native_query_servers]\nerlang = {couch_native_process, start_link, []}\n" >> /opt/couchbase/etc/couchdb/default.ini

cp /opt/couchbase/bin/membase-server /opt/couchbase/bin/membase-server.orig || true

sudo /etc/init.d/couchbase-server stop || true

sudo killall heart beam.smp || true

rm -f membase-server.num_vbuckets
wget -O membase-server.num_vbuckets https://raw.github.com/couchbaselabs/rampup/master/membase-server.num_vbuckets

sed -e "s,@@MEMBASE_NUM_VBUCKETS@@,$1,g" membase-server.num_vbuckets > \
  /opt/couchbase/bin/membase-server

sudo /etc/init.d/couchbase-server start

sleep 5 $2
