#!/usr/bin/env ruby

require 'net/http'
require 'uri'

host = ARGV[0]

n = (ARGV[1] || "1000").to_i
s = k = 0

v = ARGV[2] || "last"

extra = "gte"
if ARGV[3] == "eq"
  extra = "&endkey=%22#{k}%22"
end

a = Time.now

for x in 0..n
  uri = URI.parse("http://#{host}:5984/default/_design/rampup-#{v}/_view/#{v}?startkey=%22#{k}%22&limit=10#{extra}&stale=ok")
  Net::HTTP.new(uri.host, uri.port).start {|http|
    http.request_get(uri.request_uri)
    http.finish
  }
  k = k + 1
  k = 0 if k >= 100
end

b = Time.now
s = b - a

print "requests #{n}\n"
print "time #{s}\n"
print "req/sec #{n / s}\n"

