#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'

$host = ARGV[0] || "127.0.0.1"
$safe = true
$dbName = 'test'
$collName = 'test'

n = (ARGV[1] || "1000").to_i
s = k = 0

v = ARGV[2] || "last"

query_eq = ARGV[3] == "eq"

conn = Mongo::Connection.new($host, 27017, :safe => $safe)
db   = conn.db($dbName)
coll = db.collection($collName)

a = Time.now

for x in 0..n
  q = k.modulo(100).abs

  query = {}
  query[v] = { "$gte" => q.to_s }

  if query_eq
    query[v] = { "$eq" => q.to_s }
  end

  # Not running through the result seems, interestingly, faster.
  #
  # coll.find(query).limit(10)
  #
  coll.find(query).limit(10).each {|doc| doc }

  k = k + k.hash
end

b = Time.now
s = b - a

print "requests #{n}\n"
print "time #{s}\n"
print "req/sec #{n / s}\n"

