#!/usr/bin/env ruby

require 'rubygems'
require 'mongo'

$host = ARGV[0] || "127.0.0.1"
$safe = true
$dbName = 'test'
$collName = 'test'

n = (ARGV[1] || "1000").to_i
s = k = 0

v = ARGV[2] || "last"

query_eq = ARGV[3] == "eq"

conn = Mongo::Connection.new($host, 27017, :safe => $safe)
db   = conn.db($dbName)
coll = db.collection($collName)

for x in 0..n
  query = {}
  query[v] = { "$gte" => k.to_s }

  if query_eq
    query[v] = { "$eq" => k.to_s }
  end

  a = Time.now

  # Not running through the result seems, interestingly, faster.
  #
  # coll.find(query).limit(10)
  #
  coll.find(query).limit(10).each {|doc| doc }

  b = Time.now

  s = s + (b - a)
  k = k + 1
  k = 0 if k >= 100
end

print "requests #{n}\n"
print "time #{s}\n"
print "req/sec #{n / s}\n"

