#!/bin/sh

set -e

echo "usage : runtest couchbase*.rpm NUM_ITEMS MEMBASE_NUM_VBUCKETS [EXTRA_SLEEP]"
echo "      : runtest $1 $2 $3"

mkdir -p out

echo "# start - runtest $1 $2 $3" > out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3

killall -9 memcached || true

/etc/init.d/couchbase-server stop || true

rpm -e couchbase-server || true
rm -rf /opt/couchbase/
rpm -i $1
sleep 5 $4

/etc/init.d/couchbase-server stop

cp /opt/couchbase/etc/couchdb/default.ini /opt/couchbase/etc/couchdb/default.ini.orig

sed -e "s,@@MEMBASE_NUM_VBUCKETS@@,$3,g" membase-server.num_vbuckets > \
  /opt/couchbase/bin/membase-server

sed -e "s,os_process_limit = 50,os_process_limit = 0,g" /opt/couchbase/etc/couchdb/default.ini.orig | \
  sed -e "s,;socket_options,socket_options,g" > /opt/couchbase/etc/couchdb/default.ini

/etc/init.d/couchbase-server start
sleep 5 $4

/opt/couchbase/bin/membase cluster-init -c 127.0.0.1 \
  --cluster-init-username=Administrator \
  --cluster-init-password=password

/opt/couchbase/bin/membase bucket-create -c 127.0.0.1 \
  -u Administrator -p password \
  --bucket=default --bucket-type=membase --bucket-password= \
  --bucket-ramsize=31153 --bucket-replica=0
sleep 5 $4

curl -vX PUT http://127.0.0.1:5984/default/_design/rampup -d @rampup.json

echo "# loading membase..." >> out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3

top -u couchbase | egrep beam.smp > /tmp/top.out &

DRIVE_HOST=127.0.0.1 RATIO_SETS=1.0 RATIO_CREATES=1.0 MAX_CREATES=$2 EXIT_AFTER_CREATES=1 \
  /opt/couchbase/bin/erl -pa . /opt/couchbase/lib/ns_server/erlang/lib/ns_server-*/ebin \
  -eval 'rampup:drive_test(), init:stop().'

killall top
tail -n 50 /tmp/top.out | head -n 10 >> out/runtest-$2-$3

echo "# using membase..." >> out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3

top -u couchbase | egrep beam.smp > /tmp/top.out &

DRIVE_HOST=127.0.0.1 RATIO_SETS=0.0 MAX_OPS=10000 \
  /opt/couchbase/bin/erl -pa . /opt/couchbase/lib/ns_server/erlang/lib/ns_server-*/ebin \
  -eval 'rampup:drive_test(), init:stop().'

killall top
tail -n 50 /tmp/top.out | head -n 10 >> out/runtest-$2-$3

echo "# view building..." >> out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3

top -u couchbase | egrep beam.smp > /tmp/top.out &

/usr/bin/time -a -o out/runtest-$2-$3 curl "http://127.0.0.1:5984/default/_design/rampup/_view/random?limit=10&"

killall top
tail -n 50 /tmp/top.out | head -n 10 >> out/runtest-$2-$3

echo "# view accessing..." >> out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3

top -u couchbase | egrep beam.smp > /tmp/top.out &

./rampup-view.rb 127.0.0.1 10000 >> out/runtest-$2-$3

killall top
tail -n 50 /tmp/top.out | head -n 10 >> out/runtest-$2-$3

echo "# done - runtest $1 $2 $3" >> out/runtest-$2-$3
date +%Y%m%d-%H%M%S >> out/runtest-$2-$3
