#!/usr/bin/env ruby

if ARGV.length < 4
  print("runtest TEST_NAME PKG_RPM RAM_QUOTA REPLICA_COUNT NUM_ITEMS NUM_VBUCKETS VAL_SIZE [JOIN_URL] [EXTRA_SLEEP]\n")
  exit(-1)
end

print "runtest #{ARGV}\n"

$test_name     = ARGV[0]
$pkg           = ARGV[1]
$pkg_base      = $pkg.split('/')[-1].split('-')[0] # Ex: 'couchbase'
$ram_quota     = ARGV[2]
$replica_count = ARGV[3]
$num_items     = ARGV[4]
$num_vbuckets  = ARGV[5]
$val_size      = ARGV[6] || "1000"
$join_url      = ARGV[7]
$extra_sleep   = ARGV[8]

def run(cmd)
  print("#{cmd}\n")
  `#{cmd}`
end

run "mkdir -p out"
$out_file = "out/#{$test_name}"
run "rm -f #{$out_file}"

$time_curr = $time_start = Time.now
$time_prev = nil
$mesg_prev = nil
$step_num  = 0

def step(mesg, cmd=nil, elapsed=nil)
  $time_curr = Time.now

  if $time_prev
    elapsed = $time_curr - $time_prev unless elapsed
    `echo "# #{$step_num}. #{$mesg_prev} done. elapsed: #{elapsed}" >> #{$out_file}`
  end

  $step_num  = $step_num + 1

  `echo "# #{$step_num}. #{mesg} #{$time_curr.strftime('%Y%m%d-%H%M%S')}" >> #{$out_file}`

  $time_prev = $time_curr
  $mesg_prev = mesg

  time(cmd) if cmd
end

def time(cmd)
  system("top -u #{$pkg_base} | egrep beam.smp > /tmp/top.out &")

  run cmd

  `killall top`
  `tail -n 50 /tmp/top.out | head -n 10 >> #{$out_file}`
end

step("preparing... #{$test_name}")

run "sudo killall -9 memcached || true"

['couchbase', 'membase'].each do |x|
  run "sudo /etc/init.d/#{x}-server stop || true"
  run "sudo rpm -e #{x}-server || true"
  run "sudo rm -rf /opt/#{x}/"
end

step("installing...")

run "sudo rpm -i #{$pkg}"

sleep 5
sleep $extra_sleep.to_i if $extra_sleep

run "rm -f after-install"
run "wget https://raw.github.com/couchbaselabs/rampup/master/after-install"
run "chmod a+x after-install"
run "sudo ./after-install #{$num_vbuckets}"

step("configuring...")

if $join_url
  my_ip = `/sbin/ifconfig eth0|grep inet|awk {'print $2'}|cut -d":" -f2|head -n 1`
  run "/opt/#{$pkg_base}/bin/membase rebalance -c #{$join_url} \
    -u Administrator -p password \
    --server-add=#{my_ip}"
else
  run "/opt/#{$pkg_base}/bin/membase cluster-init -c 127.0.0.1 \
    --cluster-init-username=Administrator \
    --cluster-init-password=password"
  run "/opt/#{$pkg_base}/bin/membase bucket-create -c 127.0.0.1 \
    -u Administrator -p password \
    --bucket=default --bucket-type=membase --bucket-password= \
    --bucket-ramsize=#{$ram_quota} --bucket-replica=#{$replica_count}"
end

sleep 5
sleep $extra_sleep.to_i if $extra_sleep

run "curl -vX PUT http://127.0.0.1:5984/default/_design/rampup -d @rampup.json"

step("loading-membase...", <<EOF
     DRIVE_HOST=127.0.0.1 RATIO_SETS=1.0 RATIO_CREATES=1.0 MAX_CREATES=$3 EXIT_AFTER_CREATES=1 MIN_VALUE_SIZE=#{$val_size} \
       /opt/#{$pkg_base}/bin/erl -pa . /opt/#{$pkg_base}/lib/ns_server/erlang/lib/ns_server-*/ebin \
       -eval 'rampup:drive_test(), init:stop().'
EOF
)

step("using-membase...", <<EOF
     DRIVE_HOST=127.0.0.1 RATIO_SETS=0.0 MAX_OPS=10000 \
       /opt/#{$pkg_base}/bin/erl -pa . /opt/#{$pkg_base}/lib/ns_server/erlang/lib/ns_server-*/ebin \
       -eval 'rampup:drive_test(), init:stop().'
EOF
)

step("view-building...",
     "/usr/bin/time -a -o #{$out_file} curl -v http://127.0.0.1:5984/default/_design/rampup/_view/random?limit=10")

step("view-accessing...",
     "./rampup-view.rb 127.0.0.1 10000 >> #{$out_file}")

step("stopping...",
     "sudo /etc/init.d/#{$pkg_base}-server stop")

step("restarting...",
     "sudo /etc/init.d/#{$pkg_base}-server start")

step("warming...")

i = 0
while i < 100000
  sleep 2
  w = `/opt/#{$pkg_base}/bin/mbstats 127.0.0.1:11210 all | grep "ep_warmup:"`
  w = w.split(' ')[-1]
  break if w == "1"
  i = i + 1
end

w = `/opt/#{$pkg_base}/bin/mbstats 127.0.0.1:11210 all | grep "ep_warmup_time:"`
w = w.split(' ')[-1]

step("done...", nil, w)
